dist: trusty
sudo: required

language: node_js
node_js:
  - "v13.12.0"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get install -y dpkg
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - sudo apt-get install -f
  - ./ci/preinstall.sh

install:
  - npm install

script:
  - npm run build:prod
